name: Test image
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build Docker image
      run: docker-compose build buildroot
    - name: Test Docker image
      run: docker-compose run buildroot
